# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64

    - name: setup-maven-settings
      uses: s4u/maven-settings-action@v1
      with:
        servers: '[{"id": "github", "username": "x-access-token", "password": "${GITHUB_TOKEN}"}]'

    - name: deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GithubToken }}
      run: mvn deploy
